apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert --profile pulsar
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.network/pda-backend-pulsar: "true"
    io.kompose.service: bookie
  name: bookie
spec:
  containers:
    - args:
        - bash
        - -c
        - bin/apply-config-from-env.py conf/bookkeeper.conf && exec bin/pulsar bookie
      env:
        - name: clusterName
          value: cluster-a
        - name: metadataServiceUri
          value: metadata-store:zk:zookeeper:2181
        - name: zkServers
          value: zookeeper:2181
      image: apachepulsar/pulsar:latest
      name: bookie
      volumeMounts:
        - mountPath: /pulsar/data/bookkeeper
          name: bookie-claim0
  restartPolicy: OnFailure
  volumes:
    - name: bookie-claim0
      persistentVolumeClaim:
        claimName: bookie-claim0
