apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert --profile pulsar
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.network/pda-backend-pulsar: "true"
    io.kompose.service: broker
  name: broker
spec:
  containers:
    - args:
        - bash
        - -c
        - bin/apply-config-from-env.py conf/broker.conf &&  exec bin/pulsar broker
      env:
        - name: advertisedAddress
          value: broker
        - name: advertisedListeners
          value: external:pulsar://127.0.0.1:6650
        - name: clusterName
          value: cluster-a
        - name: managedLedgerDefaultAckQuorum
          value: "1"
        - name: managedLedgerDefaultEnsembleSize
          value: "1"
        - name: managedLedgerDefaultWriteQuorum
          value: "1"
        - name: metadataStoreUrl
          value: zk:zookeeper:2181
        - name: zookeeperServers
          value: zookeeper:2181
      image: apachepulsar/pulsar:latest
      name: broker
      ports:
        - containerPort: 6650
          hostPort: 6650
          protocol: TCP
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
  hostname: broker
  restartPolicy: OnFailure
