apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --profile pulsar
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: pulsar-init
  name: pulsar-init
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pulsar-init
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --profile pulsar
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/pda-backend-pulsar: "true"
        io.kompose.service: pulsar-init
    spec:
      containers:
        - args:
            - bin/pulsar
            - initialize-cluster-metadata
            - |2+
            - --cluster
            - cluster-a
            - |2+
            - --zookeeper
            - zookeeper:2181
            - |2+
            - --configuration-store
            - zookeeper:2181
            - |2+
            - --web-service-url
            - http://broker:8080
            - |2+
            - --broker-service-url
            - pulsar://broker:6650
          image: apachepulsar/pulsar:latest
          name: pulsar-init
      hostname: pulsar-init
      restartPolicy: Always
