apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "pda-propiedades-command"
  namespace: "default"
  labels:
    app: "pda-propiedades-command"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "pda-propiedades-command"
  template:
    metadata:
      labels:
        app: "pda-propiedades-command"
    spec:
      containers:
      - name: "pda-propiedades-command"
        image: "us-central1-docker.pkg.dev/alpes-propiedades/alpes-propiedades/propiedades-command:1.0.0"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "pda-propiedades-command"
  namespace: "default"
  labels:
    app: "pda-propiedades-command"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "pda-propiedades-command"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pda-propiedades-command-service
  namespace: default
  labels:
    app: pda-propiedades-command
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
  selector:
    app: pda-propiedades-command
