apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "pda-propiedades-query"
  namespace: "default"
  labels:
    app: "pda-propiedades-query"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "pda-propiedades-query"
  template:
    metadata:
      labels:
        app: "pda-propiedades-query"
    spec:
      containers:
      - name: "pda-propiedades-query"
        image: "us-central1-docker.pkg.dev/alpes-propiedades/alpes-propiedades/propiedades-query:1.0.1"
        env:
          - name: PULSAR_ADDRESS
            value: "35.222.56.106"
          - name: BROKER_HOST
            value: "35.222.56.106"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "pda-propiedades-query"
  namespace: "default"
  labels:
    app: "pda-propiedades-query"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "pda-propiedades-query"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pda-propiedades-query-service
  namespace: default
  labels:
    app: pda-propiedades-query
spec:
  type: ClusterIP  # Change this from LoadBalancer to ClusterIP
  ports:
    - port: 80
      targetPort: 5002
      protocol: TCP
  selector:
    app: pda-propiedades-query
